apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/overlays/openshift_vault?ref=5194cbefe5e5802e51931e105f15f62472a88ee9

namespace: spi-system

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: registry.build04.ci.openshift.org/ci-op-slsv04w1/pipeline
    newTag: redhat-appstudio-spi-image
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: registry.build04.ci.openshift.org/ci-op-slsv04w1/pipeline
    newTag: redhat-appstudio-spi-oauth-image

patches:
  - target:
      kind: ConfigMap
      name: oauth-service-environment-config
    path: oauth-service-config-patch.json
  - target:
      kind: ConfigMap
      name: shared-environment-config
    path: config-patch.json
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
  - path: delete-shared-configuration-file.yaml
